title: DevInst
description: Photo posting platform
repository: GroupDevInst/GroupDevInst.github.io
url:           "https://GroupDevInst.github.io/"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"
source: source
